#### Oppgave 3

3.1

In [1]:
from layers import *
from neural_network import NeuralNetwork
from utils import onehot
import numpy as np
from data_generators import get_train_test_sorting
import matplotlib.pyplot as plt

For å teste om lagene vi har implementert fungerer, kan vi manuelt kjøre gjennom algoritmen. Vi starter med å initalisere lagene til det nevrale nettverk.

In [2]:
#definerer variabler
r = 4
m = 4

d = 10
k = 5
p = 15
L = 2

embed = EmbedPosition(9,m,d)
att1 = Attention(d,k)
ff1 = FeedForward(d,p)
un_embed = LinearLayer(d,m)
softmax = Softmax()
loss = CrossEntropy()

Vi kan videre gi nettverket vårt en input, la oss f.eks late som vi prøver å få modellen til å sortere tallene.

In [9]:
x = np.array([[0,1,2]])
X = onehot(x, m)

print(X)

z0 = embed.forward(X)

print(z0)

z11 = att1.forward(z0)

print(z11)

z12 = ff1.forward(z11)

print(z12)
z2 = un_embed.forward(z12)

print(z2)
Z = softmax.forward(z2)

print(Z)

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]]
[[[ 0.05412351 -0.08970169 -0.13488025]
  [ 0.11435062  0.11428386 -0.08162248]
  [ 0.04683727 -0.1663157   0.08734214]
  [ 0.04124843  0.10858371  0.06586499]
  [-0.11662671  0.15176342 -0.0193181 ]
  [ 0.07456936 -0.21681149 -0.01241408]
  [-0.0036356   0.2318733   0.06160288]
  [ 0.01059464 -0.11922348  0.25638006]
  [-0.2007586   0.00620548  0.0918998 ]
  [-0.18375509  0.16314001 -0.10399757]]]
[[[ 0.06273352 -0.08982487 -0.13426984]
  [ 0.11418979  0.11256713 -0.08103296]
  [ 0.04089767 -0.16427762  0.0873991 ]
  [ 0.04809669  0.10731933  0.06336887]
  [-0.10305729  0.15552714 -0.02025011]
  [ 0.06206236 -0.22009269 -0.01523849]
  [-0.02069533  0.23084205  0.06362968]
  [ 0.00325234 -0.11830187  0.25625665]
  [-0.19517846  0.00486401  0.09224956]
  [-0.1778029   0.16274667 -0.10444467]]]
[[[ 0.06183219 -0.0901242  -0.15126668]
  [ 0.11281199  0.09973305 -0.08656429]
  [ 0.02860465 -0.15274457  0.08011932]
  [ 0.03909408  0.1289

Vi kan så teste om vi fikk riktig output, som i dette tilfelle burde være at det er $0$ på siste element. Om vi har riktig output skulle loss funksjonen vårt bli 0.

In [11]:
y = np.array([[0]])
L = loss.forward(Z,y)

print(L)

1.4296899882098888


Dette fungerte åpenbart ikke enda. Etter å ha kjørt en forward pass, er det fint å teste backwardfunksjonen til lagene. Vi starter da med å beregne den deriverte av loss funksjonen

In [12]:
dLdz = loss.backward()
d0 = softmax.backward(dLdz)
d1 = un_embed.backward(d0)
d21 = ff1.backward(d1)
d22 = att1.backward(d21)
d3 = embed.backward(d22)